# Generated by Django 4.1.13 on 2024-03-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoysHostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=100)),
                ('email', models.EmailField(default='Email', max_length=254)),
                ('phone', models.CharField(default='Email', max_length=15)),
                ('address', models.TextField(default='Address', max_length=50)),
                ('room_type', models.CharField(choices=[('A', 'AC Room'), ('N', 'Non AC Room')], default='N', max_length=1)),
                ('room_shared', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('amenities', models.TextField(default='Amenities')),
                ('in_time', models.TimeField(default='20:00:00')),
                ('warden_present', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('no_of_wardens', models.IntegerField(default='0')),
                ('food_included', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('longitude', models.DecimalField(decimal_places=8, default=0.0, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=8, default=0.0, max_digits=10)),
                ('security_present', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('for_gender', models.CharField(choices=[('B', 'Boy'), ('G', 'Girl')], default='G', max_length=1)),
                ('rules', models.TextField(default='Rules')),
                ('rating', models.FloatField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('total_reviews', models.IntegerField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('images', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BoysPg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=100)),
                ('email', models.EmailField(default='Email', max_length=254)),
                ('phone', models.CharField(default='Email', max_length=15)),
                ('address', models.TextField(default='Address', max_length=50)),
                ('room_type', models.CharField(choices=[('A', 'AC Room'), ('N', 'Non AC Room')], default='N', max_length=1)),
                ('room_shared', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('amenities', models.TextField(default='Amenities')),
                ('in_time', models.TimeField(default='20:00:00')),
                ('warden_present', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('no_of_wardens', models.IntegerField(default='0')),
                ('food_included', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('longitude', models.DecimalField(decimal_places=8, default=0.0, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=8, default=0.0, max_digits=10)),
                ('security_present', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('for_gender', models.CharField(choices=[('B', 'Boy'), ('G', 'Girl')], default='G', max_length=1)),
                ('rules', models.TextField(default='Rules')),
                ('rating', models.FloatField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('total_reviews', models.IntegerField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('images', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GirlsHostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=100)),
                ('email', models.EmailField(default='Email', max_length=254)),
                ('phone', models.CharField(default='Email', max_length=15)),
                ('address', models.TextField(default='Address', max_length=50)),
                ('room_type', models.CharField(choices=[('A', 'AC Room'), ('N', 'Non AC Room')], default='N', max_length=1)),
                ('room_shared', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('amenities', models.TextField(default='Amenities')),
                ('in_time', models.TimeField(default='20:00:00')),
                ('warden_present', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('no_of_wardens', models.IntegerField(default='0')),
                ('food_included', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('longitude', models.DecimalField(decimal_places=8, default=0.0, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=8, default=0.0, max_digits=10)),
                ('security_present', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('for_gender', models.CharField(choices=[('B', 'Boy'), ('G', 'Girl')], default='G', max_length=1)),
                ('rules', models.TextField(default='Rules')),
                ('rating', models.FloatField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('total_reviews', models.IntegerField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('images', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GirlsPg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=100)),
                ('email', models.EmailField(default='Email', max_length=254)),
                ('phone', models.CharField(default='Email', max_length=15)),
                ('address', models.TextField(default='Address', max_length=50)),
                ('room_type', models.CharField(choices=[('A', 'AC Room'), ('N', 'Non AC Room')], default='N', max_length=1)),
                ('room_shared', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('amenities', models.TextField(default='Amenities')),
                ('in_time', models.TimeField(default='20:00:00')),
                ('warden_present', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('no_of_wardens', models.IntegerField(default='0')),
                ('food_included', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('longitude', models.DecimalField(decimal_places=8, default=0.0, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=8, default=0.0, max_digits=10)),
                ('security_present', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('for_gender', models.CharField(choices=[('B', 'Boy'), ('G', 'Girl')], default='G', max_length=1)),
                ('rules', models.TextField(default='Rules')),
                ('rating', models.FloatField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('total_reviews', models.IntegerField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('images', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
