# Generated by Django 4.1.13 on 2024-03-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrape_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiffin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Name', max_length=100)),
                ('email', models.EmailField(default='Email', max_length=254)),
                ('phone', models.CharField(default='Phone', max_length=15)),
                ('address', models.TextField(default='Address', max_length=150)),
                ('longitude', models.DecimalField(decimal_places=8, default=0.0, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=8, default=0.0, max_digits=10)),
                ('menu', models.FileField(upload_to='pdfs/')),
                ('delivers_to_sp_loc', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('OpensAt', models.TimeField()),
                ('ClosesAt', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='boyshostel',
            name='address',
            field=models.TextField(default='Address', max_length=150),
        ),
        migrations.AlterField(
            model_name='boyshostel',
            name='phone',
            field=models.CharField(default='Phone', max_length=15),
        ),
        migrations.AlterField(
            model_name='boyspg',
            name='address',
            field=models.TextField(default='Address', max_length=150),
        ),
        migrations.AlterField(
            model_name='boyspg',
            name='phone',
            field=models.CharField(default='Phone', max_length=15),
        ),
        migrations.AlterField(
            model_name='girlshostel',
            name='address',
            field=models.TextField(default='Address', max_length=150),
        ),
        migrations.AlterField(
            model_name='girlshostel',
            name='phone',
            field=models.CharField(default='Phone', max_length=15),
        ),
        migrations.AlterField(
            model_name='girlspg',
            name='address',
            field=models.TextField(default='Address', max_length=150),
        ),
        migrations.AlterField(
            model_name='girlspg',
            name='phone',
            field=models.CharField(default='Phone', max_length=15),
        ),
    ]
