# Generated by Django 4.1.13 on 2024-03-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrape_data', '0002_tiffin_alter_boyshostel_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiffin',
            name='delivers_to_sp_loc',
        ),
        migrations.AddField(
            model_name='tiffin',
            name='delivers_to_loc',
            field=models.TextField(default='Delivering Location', max_length=150),
        ),
        migrations.AddField(
            model_name='tiffin',
            name='type_of_food',
            field=models.CharField(choices=[('V', 'Veg'), ('NV', 'Non-Veg')], default='V', max_length=2),
        ),
    ]
