# Generated by Django 4.1.13 on 2024-03-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrape_data', '0003_remove_tiffin_delivers_to_sp_loc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(default='Full Name', max_length=100)),
                ('email', models.EmailField(default='Email', max_length=254)),
                ('message', models.TextField(default='Message')),
            ],
        ),
    ]
