# Generated by Django 4.1.13 on 2024-03-30 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webscrape_data', '0007_student_vendor_email_vendor_name_vendor_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boyshostel',
            name='vid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webscrape_data.vendor'),
        ),
        migrations.AddField(
            model_name='boyspg',
            name='vid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webscrape_data.vendor'),
        ),
        migrations.AddField(
            model_name='girlshostel',
            name='vid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webscrape_data.vendor'),
        ),
        migrations.AddField(
            model_name='girlspg',
            name='vid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webscrape_data.vendor'),
        ),
    ]
