# Generated by Django 4.1.13 on 2024-04-03 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webscrape_data', '0008_boyshostel_vid_boyspg_vid_girlshostel_vid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiffin',
            name='vid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webscrape_data.vendor'),
        ),
    ]
