# Generated by Django 4.1.13 on 2024-04-03 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webscrape_data', '0009_tiffin_vid'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='service_name',
            field=models.CharField(default='Service Name', max_length=255),
        ),
        migrations.AddField(
            model_name='review',
            name='sid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webscrape_data.student'),
        ),
        migrations.AddField(
            model_name='review',
            name='type',
            field=models.CharField(choices=[('H', 'Hostel'), ('P', 'PG'), ('T', 'Tiffin')], default='Hostel', max_length=2),
        ),
    ]
