# Generated by Django 4.1.13 on 2024-04-03 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscrape_data', '0010_review_service_name_review_sid_review_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='sid',
        ),
    ]
