# Generated by Django 4.1.13 on 2024-03-30 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('AdminId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('ReviewId', models.AutoField(primary_key=True, serialize=False)),
                ('StudentId', models.IntegerField()),
                ('Message', models.TextField()),
                ('Photos', models.BinaryField()),
                ('Rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=254)),
                ('Password', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=15)),
                ('Type', models.CharField(choices=[('Student', 'Student'), ('Vendor', 'Vendor'), ('Admin', 'Admin')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('VendorId', models.AutoField(primary_key=True, serialize=False)),
                ('TypeOfBusiness', models.CharField(choices=[('Hostel', 'Hostel'), ('PG', 'PG'), ('TiffinServiceProvider', 'TiffinServiceProvider')], max_length=21)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webscraping.user')),
            ],
        ),
        migrations.CreateModel(
            name='TiffinServiceProvider',
            fields=[
                ('TiffinId', models.AutoField(primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=255)),
                ('Longitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('Latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('Menu', models.TextField()),
                ('DeliveryLocation', models.CharField(max_length=255)),
                ('OpensAt', models.TimeField()),
                ('ClosesAt', models.TimeField()),
                ('VendorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webscraping.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentId', models.AutoField(primary_key=True, serialize=False)),
                ('UniversityName', models.CharField(max_length=255)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webscraping.user')),
            ],
        ),
        migrations.CreateModel(
            name='PGOwner',
            fields=[
                ('PGId', models.AutoField(primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=255)),
                ('Longitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('Latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('Amenities', models.TextField()),
                ('InTime', models.TimeField()),
                ('RoomAvailable', models.IntegerField()),
                ('WardenPresent', models.BooleanField()),
                ('NumberOfWarden', models.IntegerField()),
                ('FoodIncludes', models.TextField()),
                ('ForGender', models.CharField(choices=[('Boy', 'Boy'), ('Girl', 'Girl')], max_length=4)),
                ('Security', models.BooleanField()),
                ('VendorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webscraping.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='HostelOwner',
            fields=[
                ('HostelId', models.AutoField(primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=255)),
                ('Longitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('Latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('Amenities', models.TextField()),
                ('InTime', models.TimeField()),
                ('RoomAvailable', models.IntegerField()),
                ('WardenPresent', models.BooleanField()),
                ('NumberOfWarden', models.IntegerField()),
                ('FoodIncludes', models.TextField()),
                ('ForGender', models.CharField(choices=[('Boy', 'Boy'), ('Girl', 'Girl')], max_length=4)),
                ('Security', models.BooleanField()),
                ('VendorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webscraping.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('ContactId', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=254)),
                ('Message', models.TextField()),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webscraping.user')),
            ],
        ),
    ]
