# Generated by Django 4.1.13 on 2024-03-27 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webscraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('total_reviews', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('images', models.TextField(blank=True, null=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('opening_time', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('doc_id', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('web_url', models.URLField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoysPg',
            fields=[
                ('pg_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webscraping.pg')),
            ],
            bases=('webscraping.pg',),
        ),
        migrations.CreateModel(
            name='GirlsPg',
            fields=[
                ('pg_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webscraping.pg')),
            ],
            bases=('webscraping.pg',),
        ),
    ]
