# Generated by Django 4.1.13 on 2024-03-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraping', '0002_pg_boyspg_girlspg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boyshostel',
            name='area',
        ),
        migrations.RemoveField(
            model_name='boyshostel',
            name='doc_id',
        ),
        migrations.RemoveField(
            model_name='boyshostel',
            name='opening_time',
        ),
        migrations.RemoveField(
            model_name='boyshostel',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='boyshostel',
            name='scraped_at',
        ),
        migrations.RemoveField(
            model_name='boyshostel',
            name='type',
        ),
        migrations.RemoveField(
            model_name='boyshostel',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='boyshostel',
            name='video',
        ),
        migrations.RemoveField(
            model_name='boyshostel',
            name='web_url',
        ),
        migrations.RemoveField(
            model_name='girlshostel',
            name='area',
        ),
        migrations.RemoveField(
            model_name='girlshostel',
            name='doc_id',
        ),
        migrations.RemoveField(
            model_name='girlshostel',
            name='opening_time',
        ),
        migrations.RemoveField(
            model_name='girlshostel',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='girlshostel',
            name='scraped_at',
        ),
        migrations.RemoveField(
            model_name='girlshostel',
            name='type',
        ),
        migrations.RemoveField(
            model_name='girlshostel',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='girlshostel',
            name='video',
        ),
        migrations.RemoveField(
            model_name='girlshostel',
            name='web_url',
        ),
        migrations.AddField(
            model_name='boyshostel',
            name='amenities',
            field=models.TextField(default='Default Amentities'),
        ),
        migrations.AddField(
            model_name='boyshostel',
            name='email',
            field=models.EmailField(default='Default Name', max_length=254),
        ),
        migrations.AddField(
            model_name='boyshostel',
            name='food_included',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boyshostel',
            name='for_boy_or_girl',
            field=models.CharField(choices=[('B', 'Boy'), ('G', 'Girl')], default='G', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boyshostel',
            name='in_time',
            field=models.TimeField(default='20:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boyshostel',
            name='no_of_wardens',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boyshostel',
            name='room_shared',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='y', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boyshostel',
            name='room_type',
            field=models.CharField(choices=[('A', 'AC Room'), ('N', 'Non AC Room')], default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boyshostel',
            name='security_present',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boyshostel',
            name='warden_present',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='girlshostel',
            name='amenities',
            field=models.TextField(default='Default Amentities'),
        ),
        migrations.AddField(
            model_name='girlshostel',
            name='email',
            field=models.EmailField(default='Default Name', max_length=254),
        ),
        migrations.AddField(
            model_name='girlshostel',
            name='food_included',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='girlshostel',
            name='for_boy_or_girl',
            field=models.CharField(choices=[('B', 'Boy'), ('G', 'Girl')], default='G', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='girlshostel',
            name='in_time',
            field=models.TimeField(default='20:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='girlshostel',
            name='no_of_wardens',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='girlshostel',
            name='room_shared',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='girlshostel',
            name='room_type',
            field=models.CharField(choices=[('A', 'AC Room'), ('N', 'Non AC Room')], default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='girlshostel',
            name='security_present',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='girlshostel',
            name='warden_present',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boyshostel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='boyshostel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='boyshostel',
            name='phone',
            field=models.CharField(default='1234567890', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='girlshostel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='girlshostel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='girlshostel',
            name='phone',
            field=models.CharField(default='1234567890', max_length=15),
            preserve_default=False,
        ),
    ]
