# Generated by Django 4.1.13 on 2024-03-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraping', '0003_remove_boyshostel_area_remove_boyshostel_doc_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boyshostel',
            name='rules',
            field=models.TextField(default='Default Rules'),
        ),
        migrations.AddField(
            model_name='girlshostel',
            name='rules',
            field=models.TextField(default='Default Rules'),
        ),
    ]
